Repository mrapp-ke/MLRL-Boomer, pull requests merged in 2024-04, with the labels that each got.

#828 Link statically against library "mlrlcommon"
  cpp/subprojects/common/meson.build
Labels: compilation

#829 Use links to documentation rather than to files in the repository
  README.md
  python/subprojects/common/README.md
  python/subprojects/seco/README.md
  python/subprojects/testbed/README.md
Labels: documentation

#830 Link to latest documentation
  README.md
  python/subprojects/common/README.md
  python/subprojects/seco/README.md
  python/subprojects/testbed/README.md
Labels: documentation

#831 Fix link in README
  README.md
Labels: documentation

#832 Allow to restrict build to individual subprojects
  cpp/meson.build
  cpp/meson.options
  doc/developer_guide/compilation.md
  python/meson.build
  python/meson.options
  scons/compilation.py
  scons/documentation.py
  scons/environment.py
  scons/modules.py
  scons/packaging.py
  scons/sconstruct.py
Labels: compilation

#834 Add separate workflow for building the documentation
  .github/workflows/test_build.yml
  .github/workflows/test_doc.yml
  CHANGELOG.md
  doc/developer_guide/coding_standards.md
Labels: ci

#833 Add Github workflow for testing the publishing of packages
  .github/workflows/do_publish.yml
  .github/workflows/publish.yml
  .github/workflows/schedule_publish.yml
  .github/workflows/template_publish.yml
  .github/workflows/template_publish_non_native.yml
  .github/workflows/template_publish_platform.yml
  .github/workflows/template_publish_pure.yml
  .github/workflows/test_build.yml
  .github/workflows/test_format.yml
  .github/workflows/test_publish.yml
  CHANGELOG.md
  build
  build.bat
  cpp/subprojects/common/src/mlrl/common/model/condition_list.cpp
  doc/developer_guide/coding_standards.md
  scons/command_line.py
  scons/compilation.py
  scons/run.py
Labels: ci

#836 Use unique version for development releases
  .github/workflows/do_publish.yml
  .github/workflows/schedule_publish.yml
  .github/workflows/template_publish.yml
  .github/workflows/template_publish_non_native.yml
  .github/workflows/template_publish_platform.yml
  .github/workflows/template_publish_pure.yml
  .github/workflows/test_file_changes.yml
  .github/workflows/test_publish.yml
  VERSION.dev
  scons/sconstruct.py
  scons/versioning.py
Labels: ci

#837 Update workflow triggers
  .github/workflows/release.yml
  .github/workflows/release_development.yml
  .github/workflows/template_publish_non_native.yml
  .github/workflows/template_publish_platform.yml
  .github/workflows/template_publish_pure.yml
  .github/workflows/test_release.yml
  doc/developer_guide/coding_standards.md
Labels: ci

#838 Use Github app for generating tokens
  .github/workflows/test_file_changes.yml
Labels: ci

#840 Manage release branches via CI
  .github/workflows/merge_bugfix.yml
  .github/workflows/merge_feature.yml
  .github/workflows/release.yml
  .github/workflows/release_development.yml
  .github/workflows/test_file_changes.yml
  CHANGELOG.md
  doc/developer_guide/coding_standards.md
  scons/sconstruct.py
  scons/versioning.py
Labels: ci

#841 Fix release workflow
  .github/workflows/release.yml
Labels: ci

#845 Fix workflow that checks for disallowed changes
  .github/workflows/test_file_changes.yml
Labels: bug, ci

#851 Remove test file changes workflow
  .github/workflows/test_file_changes.yml
Labels: ci

#852 Add section "Prediction Characteristics" to the documentation
  doc/developer_guide/coding_standards.md
  doc/quickstart/testbed.md
  doc/user_guide/testbed/evaluation.md
  doc/user_guide/testbed/experimental_results.md
  doc/user_guide/testbed/model_persistence.md
  doc/user_guide/testbed/parameter_persistence.md
  doc/user_guide/testbed/pre_processing.md
Labels: documentation

#855 Prevent newline from being added to the VERSION file
  .github/workflows/merge_bugfix.yml
  .github/workflows/merge_feature.yml
Labels: bug, ci

#856 Prevent newline from being added to the VERSION file
  .github/workflows/merge_bugfix.yml
  .github/workflows/merge_feature.yml
Labels: bug, ci

#859 Add missing sections to documentation
  doc/developer_guide/compilation.md
  doc/developer_guide/documentation.md
  doc/user_guide/boosting/parameters.md
  doc/user_guide/seco/parameters.md
  doc/user_guide/testbed/arguments.md
  doc/user_guide/testbed/evaluation.md
  doc/user_guide/testbed/experimental_results.md
  doc/user_guide/testbed/model_persistence.md
  doc/user_guide/testbed/parameter_persistence.md
  doc/user_guide/testbed/pre_processing.md
Labels: documentation
