Repository mrapp-ke/MLRL-Boomer, pull requests merged in 2024-03, with the labels that each got.

#816 Readthedocs Integration
  .readthedocs.yaml
  doc/developer_guide/documentation.md
  scons/modules.py
Labels: documentation, compilation

#817 Install OpenCL headers for readthedocs build
  .readthedocs.yaml
Labels: documentation, compilation

#818 Disable GPU support for readthedocs build
  .readthedocs.yaml
Labels: documentation, compilation

#819 Fix environment variables used for readthedocs build
  .readthedocs.yaml
Labels: documentation, compilation

#820 Add "setuptools" as a dependency
  scons/dependencies.py
  scons/packaging.py
  scons/requirements.txt
Labels: compilation

#821 Create link to the output of a readthedocs build
  .readthedocs.yaml
Labels: documentation, compilation

#822 Copy results of readthedocs build into output directory
  .readthedocs.yaml
Labels: documentation, compilation

#823 Add code of conduct to documentation
  CODE_OF_CONDUCT.md
  doc/index.md
  doc/misc/CODE_OF_CONDUCT.md
Labels: documentation

#824 Run workflows for pull requests
  .github/workflows/test_build.yml
  .github/workflows/test_format.yml
  doc/developer_guide/coding_standards.md
Labels: ci

#825 Do not use Github action JesseTG/rm
  .github/workflows/test_build.yml
Labels: ci

#826 Update dependency "build"
  scons/requirements.txt
Labels: compilation
